import sympy as sp

import mwmath.adjacency_matrices as am

# establish symbols for each space
IBERIA_CITIES = (
    santander,
    saragossa,
    barcelona,
    lisbon,
    madrid,
    alicante,
    cadiz,
    granada,
) = sp.symbols(
    """
    santander,
    saragossa,
    barcelona,
    lisbon,
    madrid,
    alicante,
    cadiz,
    granada
"""
)

IBERIA_ROAD_CONNECTIONS: am.SymbolicConnections = {
    santander: {saragossa, madrid, lisbon},
    saragossa: {barcelona, alicante, madrid, santander},
    barcelona: {saragossa},
    lisbon: {santander, madrid, cadiz},
    madrid: {santander, saragossa, alicante, granada, cadiz, lisbon},
    alicante: {granada, madrid, saragossa},
    cadiz: {lisbon, madrid, granada},
    granada: {alicante, cadiz, madrid},
}

IBERIA_RAIL_CONNECTIONS: am.SymbolicConnections = {
    santander: {madrid},
    saragossa: {barcelona, madrid},
    barcelona: {saragossa, alicante},
    lisbon: {madrid},
    madrid: {santander, saragossa, alicante, lisbon},
    alicante: {barcelona, madrid},
}

assert am.vertex_degrees(IBERIA_ROAD_CONNECTIONS) == {
    santander: 3,
    saragossa: 4,
    barcelona: 1,
    lisbon: 3,
    madrid: 6,
    alicante: 3,
    cadiz: 3,
    granada: 3,
}

assert am.vertex_degrees(IBERIA_RAIL_CONNECTIONS) == {
    santander: 1,
    saragossa: 2,
    barcelona: 2,
    lisbon: 1,
    madrid: 4,
    alicante: 2,
}

IBERIA_ROAD_MATRIX = am.build_matrix_symbolic(IBERIA_CITIES, IBERIA_ROAD_CONNECTIONS)
IBERIA_RAIL_MATRIX = am.build_matrix_symbolic(IBERIA_CITIES, IBERIA_RAIL_CONNECTIONS)
IBERIA_MATRIX = IBERIA_ROAD_MATRIX + IBERIA_RAIL_MATRIX

assert IBERIA_ROAD_MATRIX.is_symmetric()
assert IBERIA_RAIL_MATRIX.is_symmetric()

CITIES = (
    alicante,
    amsterdam,
    athens,
    barcelona,
    bari,
    belgrade,
    berlin,
    bordeaux,
    brussels,
    bucharest,
    budapest,
    cadiz,
    cagliari,
    castle_dracula,
    clermont_ferrand,
    cologne,
    constanta,
    dublin,
    edinburgh,
    florence,
    frankfurt,
    galatz,
    galway,
    geneva,
    genoa,
    granada,
    hamburg,
    klausenburg,
    le_havre,
    leipzig,
    lisbon,
    liverpool,
    london,
    madrid,
    manchester,
    marseilles,
    milan,
    munich,
    nantes,
    naples,
    nuremberg,
    paris,
    plymouth,
    prague,
    rome,
    salonica,
    santander,
    saragossa,
    sarajevo,
    sofia,
    strasbourg,
    swansea,
    szeged,
    toulouse,
    valona,
    varna,
    venice,
    vienna,
    zagreb,
    zurich,
) = sp.symbols(
    """
    alicante,
    amsterdam,
    athens,
    barcelona,
    bari,
    belgrade,
    berlin,
    bordeaux,
    brussels,
    bucharest,
    budapest,
    cadiz,
    cagliari,
    castle_dracula,
    clermont_ferrand,
    cologne,
    constanta,
    dublin,
    edinburgh,
    florence,
    frankfurt,
    galatz,
    galway,
    geneva,
    genoa,
    granada,
    hamburg,
    klausenburg,
    le_havre,
    leipzig,
    lisbon,
    liverpool,
    london,
    madrid,
    manchester,
    marseilles,
    milan,
    munich,
    nantes,
    naples,
    nuremberg,
    paris,
    plymouth,
    prague,
    rome,
    salonica,
    santander,
    saragossa,
    sarajevo,
    sofia,
    strasbourg,
    swansea,
    szeged,
    toulouse,
    valona,
    varna,
    venice,
    vienna,
    zagreb,
    zurich,
"""
)

SEAS = (
    adriatic_sea,
    black_sea,
    english_channel,
    ionian_sea,
    irish_sea,
    mediterranean_sea,
    north_atlantic,
    north_sea,
    south_atlantic,
    tyrrhenian_sea,
) = sp.symbols(
    """
    adriatic_sea,
    black_sea,
    english_channel,
    ionian_sea,
    irish_sea,
    mediterranean_sea,
    north_atlantic,
    north_sea,
    south_atlantic,
    tyrrhenian_sea
"""
)

SPACES = CITIES + SEAS

ROAD_CONNECTIONS: am.SymbolicConnections = {
    alicante: {granada, madrid, saragossa},
    amsterdam: {brussels, cologne},
    athens: {valona},
    barcelona: {saragossa, toulouse},
    bari: {naples, rome},
    belgrade: {sarajevo, szeged, klausenburg, bucharest, sofia},
    berlin: {prague, leipzig, hamburg},
    bordeaux: {santander, nantes, clermont_ferrand, toulouse},
    brussels: {paris, le_havre, amsterdam, cologne, strasbourg},
    bucharest: {sofia, belgrade, klausenburg, galatz, constanta},
    budapest: {zagreb, vienna, klausenburg, szeged},
    cadiz: {lisbon, madrid, granada},
    castle_dracula: {klausenburg, galatz},
    clermont_ferrand: {toulouse, bordeaux, nantes, paris, geneva, marseilles},
    cologne: {strasbourg, brussels, amsterdam, hamburg, leipzig, frankfurt},
    constanta: {bucharest, varna},
    dublin: {galway},
    edinburgh: {manchester},
    florence: {genoa, venice, rome},
    frankfurt: {strasbourg, cologne, leipzig, nuremberg},
    galatz: {bucharest, klausenburg, castle_dracula},
    galway: {dublin},
    geneva: {marseilles, clermont_ferrand, paris, strasbourg, zurich},
    genoa: {marseilles, venice, florence},
    granada: {cadiz, madrid, alicante},
    hamburg: {cologne, berlin, leipzig},
    klausenburg: {budapest, szeged, belgrade, bucharest, castle_dracula, galatz},
    le_havre: {nantes, paris, brussels},
    leipzig: {hamburg, cologne, frankfurt, nuremberg, berlin},
    lisbon: {santander, madrid, cadiz},
    liverpool: {manchester, swansea},
    london: {manchester, swansea, plymouth},
    madrid: {santander, lisbon, cadiz, granada, alicante, saragossa},
    manchester: {edinburgh, liverpool, london},
    marseilles: {toulouse, clermont_ferrand, geneva, zurich, milan, genoa},
    milan: {zurich, munich, venice, marseilles},
    munich: {nuremberg, zurich, milan, venice, zagreb, vienna},
    nantes: {le_havre, paris, clermont_ferrand, bordeaux},
    naples: {rome, bari},
    nuremberg: {leipzig, frankfurt, strasbourg, zurich, munich, prague},
    paris: {brussels, le_havre, nantes, clermont_ferrand, geneva, strasbourg},
    plymouth: {london},
    prague: {berlin, nuremberg, vienna},
    rome: {florence, naples, bari},
    salonica: {valona, sofia},
    santander: {bordeaux, saragossa, madrid, lisbon},
    saragossa: {santander, madrid, alicante, barcelona, toulouse},
    sarajevo: {zagreb, belgrade, sofia, valona},
    sofia: {belgrade, sarajevo, valona, salonica, varna, bucharest},
    strasbourg: {brussels, paris, geneva, zurich, nuremberg, frankfurt, cologne},
    swansea: {liverpool, london},
    szeged: {budapest, zagreb, belgrade, klausenburg},
    toulouse: {bordeaux, saragossa, barcelona, marseilles, clermont_ferrand},
    valona: {sarajevo, sofia, salonica, athens},
    varna: {constanta, sofia},
    venice: {munich, milan, genoa, florence},
    vienna: {prague, munich, zagreb, budapest},
    zagreb: {munich, vienna, budapest, szeged, sarajevo},
    zurich: {strasbourg, geneva, marseilles, milan, munich, nuremberg},
}

YELLOW_RAIL_CONNECTIONS: am.SymbolicConnections = {
    bari: {naples},
    belgrade: {szeged, sofia},
    berlin: {prague},
    bucharest: {szeged, constanta, galatz},
    budapest: {vienna, szeged},
    constanta: {bucharest},
    florence: {genoa, rome},
    galatz: {bucharest},
    geneva: {milan},
    genoa: {milan, venice, florence},
    marseilles: {milan},
    milan: {zurich, genoa, geneva, marseilles},
    naples: {rome, bari},
    prague: {berlin, vienna},
    rome: {florence, naples},
    salonica: {sofia},
    sofia: {belgrade, salonica, varna},
    szeged: {budapest, bucharest, belgrade},
    varna: {sofia},
    venice: {vienna, genoa},
    vienna: {prague, budapest, venice},
    zurich: {milan},
}

WHITE_RAIL_CONNECTIONS: am.SymbolicConnections = {
    alicante: {madrid, barcelona},
    barcelona: {alicante, saragossa},
    berlin: {hamburg, cologne, leipzig},
    bordeaux: {paris, saragossa},
    brussels: {paris, cologne},
    cologne: {brussels, frankfurt, berlin},
    edinburgh: {manchester},
    frankfurt: {cologne, leipzig, strasbourg},
    hamburg: {berlin},
    le_havre: {paris},
    leipzig: {berlin, frankfurt, nuremberg},
    lisbon: {madrid},
    liverpool: {manchester},
    london: {manchester, swansea, plymouth},
    madrid: {santander, lisbon, alicante, saragossa},
    manchester: {edinburgh, liverpool, london},
    marseilles: {paris},
    munich: {nuremberg, strasbourg},
    nuremberg: {munich, leipzig},
    paris: {le_havre, bordeaux, marseilles, brussels},
    plymouth: {london},
    santander: {madrid},
    saragossa: {madrid, barcelona, bordeaux},
    strasbourg: {frankfurt, munich, zurich},
    swansea: {london},
    zurich: {strasbourg},
}

SEA_CONNECTIONS: am.SymbolicConnections = {
    adriatic_sea: {venice, valona, ionian_sea, bari},
    venice: {adriatic_sea},
    valona: {adriatic_sea},
    bari: {adriatic_sea},
    black_sea: {constanta, varna, ionian_sea},
    constanta: {black_sea},
    varna: {black_sea},
    english_channel: {north_sea, le_havre, north_atlantic, plymouth, london},
    le_havre: {english_channel},
    plymouth: {english_channel},
    london: {english_channel},
    ionian_sea: {adriatic_sea, salonica, athens, tyrrhenian_sea, black_sea},
    salonica: {ionian_sea},
    athens: {ionian_sea},
    irish_sea: {dublin, liverpool, swansea, north_atlantic},
    dublin: {irish_sea},
    liverpool: {irish_sea},
    swansea: {irish_sea},
    mediterranean_sea: {
        marseilles,
        barcelona,
        alicante,
        cagliari,
        tyrrhenian_sea,
        south_atlantic,
    },
    marseilles: {mediterranean_sea},
    barcelona: {mediterranean_sea},
    alicante: {mediterranean_sea},
    cagliari: {mediterranean_sea, tyrrhenian_sea},
    north_atlantic: {
        galway,
        irish_sea,
        english_channel,
        nantes,
        bordeaux,
        north_sea,
        south_atlantic,
    },
    galway: {north_atlantic},
    nantes: {north_atlantic},
    bordeaux: {north_atlantic},
    north_sea: {edinburgh, amsterdam, hamburg, north_atlantic, english_channel},
    edinburgh: {north_sea},
    amsterdam: {north_sea},
    hamburg: {north_sea},
    south_atlantic: {santander, lisbon, cadiz, north_atlantic, mediterranean_sea},
    santander: {south_atlantic},
    lisbon: {south_atlantic},
    cadiz: {south_atlantic},
    tyrrhenian_sea: {genoa, rome, naples, cagliari, mediterranean_sea, ionian_sea},
    genoa: {tyrrhenian_sea},
    rome: {tyrrhenian_sea},
    naples: {tyrrhenian_sea},
    # cagliari: {mediterranean_sea, tyrrhenian_sea},  # included above with mediterranean_sea
}

assert am.vertex_degrees(ROAD_CONNECTIONS) == {
    alicante: 3,
    amsterdam: 2,
    athens: 1,
    barcelona: 2,
    bari: 2,
    belgrade: 5,
    berlin: 3,
    bordeaux: 4,
    brussels: 5,
    bucharest: 5,
    budapest: 4,
    cadiz: 3,
    castle_dracula: 2,
    clermont_ferrand: 6,
    cologne: 6,
    constanta: 2,
    dublin: 1,
    edinburgh: 1,
    florence: 3,
    frankfurt: 4,
    galatz: 3,
    galway: 1,
    geneva: 5,
    genoa: 3,
    granada: 3,
    hamburg: 3,
    klausenburg: 6,
    le_havre: 3,
    leipzig: 5,
    lisbon: 3,
    liverpool: 2,
    london: 3,
    madrid: 6,
    manchester: 3,
    marseilles: 6,
    milan: 4,
    munich: 6,
    nantes: 4,
    naples: 2,
    nuremberg: 6,
    paris: 6,
    plymouth: 1,
    prague: 3,
    rome: 3,
    salonica: 2,
    santander: 4,
    saragossa: 5,
    sarajevo: 4,
    sofia: 6,
    strasbourg: 7,
    swansea: 2,
    szeged: 4,
    toulouse: 5,
    valona: 4,
    varna: 2,
    venice: 4,
    vienna: 4,
    zagreb: 5,
    zurich: 6,
}

assert am.vertex_degrees(YELLOW_RAIL_CONNECTIONS) == {
    bari: 1,
    belgrade: 2,
    berlin: 1,
    bucharest: 3,
    budapest: 2,
    constanta: 1,
    florence: 2,
    galatz: 1,
    geneva: 1,
    genoa: 3,
    marseilles: 1,
    milan: 4,
    naples: 2,
    prague: 2,
    rome: 2,
    salonica: 1,
    sofia: 3,
    szeged: 3,
    varna: 1,
    venice: 2,
    vienna: 3,
    zurich: 1,
}

assert am.vertex_degrees(WHITE_RAIL_CONNECTIONS) == {
    alicante: 2,
    barcelona: 2,
    berlin: 3,
    bordeaux: 2,
    brussels: 2,
    cologne: 3,
    edinburgh: 1,
    frankfurt: 3,
    hamburg: 1,
    le_havre: 1,
    leipzig: 3,
    lisbon: 1,
    liverpool: 1,
    london: 3,
    madrid: 4,
    manchester: 3,
    marseilles: 1,
    munich: 2,
    nuremberg: 2,
    paris: 4,
    plymouth: 1,
    santander: 1,
    saragossa: 3,
    strasbourg: 3,
    swansea: 1,
    zurich: 1,
}

assert am.vertex_degrees(SEA_CONNECTIONS) == {
    adriatic_sea: 4,
    valona: 1,
    venice: 1,
    bari: 1,
    black_sea: 3,
    varna: 1,
    constanta: 1,
    english_channel: 5,
    le_havre: 1,
    plymouth: 1,
    london: 1,
    ionian_sea: 5,
    salonica: 1,
    athens: 1,
    irish_sea: 4,
    liverpool: 1,
    swansea: 1,
    dublin: 1,
    mediterranean_sea: 6,
    cagliari: 2,
    alicante: 1,
    barcelona: 1,
    marseilles: 1,
    north_atlantic: 7,
    galway: 1,
    nantes: 1,
    bordeaux: 1,
    north_sea: 5,
    hamburg: 1,
    amsterdam: 1,
    edinburgh: 1,
    south_atlantic: 5,
    santander: 1,
    lisbon: 1,
    cadiz: 1,
    tyrrhenian_sea: 6,
    naples: 1,
    rome: 1,
    genoa: 1,
    # cagliari also in mediterranean sea
}

IDENTITY_MATRIX = sp.eye(len(SPACES))
ROAD_MATRIX = am.build_matrix_symbolic(SPACES, ROAD_CONNECTIONS)
YELLOW_MATRIX = am.build_matrix_symbolic(SPACES, YELLOW_RAIL_CONNECTIONS)
WHITE_MATRIX = am.build_matrix_symbolic(SPACES, WHITE_RAIL_CONNECTIONS)
SEA_MATRIX = am.build_matrix_symbolic(SPACES, SEA_CONNECTIONS)
TRAVEL_MATRIX = (
    IDENTITY_MATRIX
    + ROAD_MATRIX
    + (YELLOW_MATRIX + WHITE_MATRIX)
    + (YELLOW_MATRIX + WHITE_MATRIX) ** 2
    + WHITE_MATRIX**3
    + SEA_MATRIX
)

assert IDENTITY_MATRIX.is_symmetric()
assert ROAD_MATRIX.is_symmetric()
assert YELLOW_MATRIX.is_symmetric()
assert WHITE_MATRIX.is_symmetric()
assert SEA_MATRIX.is_symmetric()

if __name__ == "__main__":
    ...
